[metadata]
name = usawa
version = 0.2.0
description = Signed, immutable accounting.
author = Louis Holbrook
author_email = dev@holbrook.no
url = https://git.defalsify.org/usawa
keywords =
	accounting
	cryptography
classifiers =
	Environment :: No Input/Output (Daemon)
	Programming Language :: Python :: 3
	Operating System :: OS Independent
	Development Status :: 3 - Alpha
	Intended Audience :: Developers
	License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
#	Topic :: Blockchain :: EVM
license = GPL3
licence_files =
	LICENSE

[options]
include_package_data = True
python_requires = >= 3.7
packages = 
	usawa
	usawa.resolve
	usawa.runnable
	usawa.gui
	usawa.gui.core
	usawa.gui.components
	usawa.gui.controllers
	usawa.gui.models
	usawa.gui.views
	usawa.storage

[options.entry_points]
console_scripts =
	usawad = usawa.runnable.server:main
	usawa-gui = usawa.runnable.gui:main
	usawa-create = usawa.runnable.create:main
	usawa-add = usawa.runnable.add:main
	usawa-entry = usawa.runnable.entry:main
	usawa-wallet = usawa.runnable.wallet:main
	usawa-view = usawa.runnable.view:main
	usawa-import = usawa.runnable.import:main
	usawa-export = usawa.runnable.export:main
