\input texinfo
@settitle usawa

@copying
Documentation released 2026 under CC-BY-SA
@end copying

@titlepage
@title usawa
@author Louis Holbrook
@end titlepage

@c
@contents

@ifnottex
@node Top
@top Introduction
@end ifnottex

@include intro.texi
@include xml.texi
@include ledger.texi
@include accounts.texi
@include unit.texi
@include identity.texi
@include time.texi
@include resolver.texi
@include assets.texi
@include internals.texi
@include appendix.texi
